#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - core

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  project_feed: true
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build:
  publish_nuget: true
  publish_nuget_symbols: true

init:
- ps: |
  $tag = $(git tag -l --points-at HEAD)
  $revision = @{ $true = "{0:00000}" -f [convert]::ToInt32("0" + $env:APPVEYOR_BUILD_NUMBER, 10); $false = "local" }[$env:APPVEYOR_BUILD_NUMBER -ne $NULL];
  $suffix = @{ $true = ""; $false = "ci-$revision"}[$tag -ne $NULL -and $revision -ne "local"]
  $commitHash = $(git rev-parse --short HEAD)
  $buildSuffix = @{ $true = "$($suffix)-$($commitHash)"; $false = "$($branch)-$($commitHash)" }[$suffix -ne ""]

  $Env:SUFFIX = $suffix
  $Env:BUILDSUFFIX = $buildSuffix

before_build:
- appveyor-retry dotnet restore "Dapper.AmbientContext.sln" -v Minimal

build_script:
- dotnet build "Dapper.AmbientContext.sln" -c %CONFIGURATION% --no-dependencies --version-suffix %BUILDSUFFIX%

after_build:
- dotnet pack "src\Dapper.AmbientContext\Dapper.AmbientContext.csproj" -c %CONFIGURATION% --include-symbols --no-build --version-suffix %SUFFIX% -o artifacts

test_script:
- dotnet test "test\Dapper.AmbientContext.Tests\Dapper.AmbientContext.Tests.csproj" --no-build -c %CONFIGURATION%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src\Dapper.AmbientContext\artifacts\**\*.*