#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

cache:
  - packages -> **\packages.config

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: Dapper.AmbientContext.sln
  publish_nuget: true
  publish_nuget_symbols: true

  verbosity: normal

before_build:
  - nuget restore

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '*.nupkg'
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key:
      secure: ZyNMTHl83Q+jbtyCaweu6ULT7jo2dGq+lF7TibDcVyE1aH9KKvdmf9FEHkRQHVCL
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true  
