#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - core

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  project_feed: true
  disable_publish_on_pr: true

cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%LocalAppData%\.nuget\packages'

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\Dapper.AmbientContext" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "test\Dapper.AmbientContext.Tests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
- dotnet pack "src\Dapper.AmbientContext" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

test_script:
- dotnet test "test\Dapper.AmbientContext.Tests\Dapper.AmbientContext.Tests.csproj" -c %CONFIGURATION%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src\Dapper.AmbientContext\artifacts\**\*.*